source 'https://cdn.cocoapods.org/'
source 'https://github.com/thecarevoice/carevoiceos-design-sdk-spec.git'
source 'https://github.com/thecarevoice/carevoiceos-common-sdk-spec.git'
source 'https://github.com/thecarevoice/carevoiceos-ios-sdk-spec.git'
platform :ios, '14.0'

target 'CareVoiceOSDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CareVoiceOSDemo
  pod 'JWTDecode', '~> 3.3'
  
  pod 'CVDesign/iOS', '3.1.1'
  pod 'CVCommon/iOS', '3.1.1'
  pod 'CVWellness/iOS', '3.1.1'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
